services:
  ai:
    build:
      context: ./ai
      dockerfile: ./serving/Dockerfile
    environment:
      - AI_REQUIRE_MODEL=0 # set to 1 and provide GOOGLE_API_KEY for real model
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - ./.env
    ports:
      - "8600:8600"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai:8600
    depends_on:
      - ai
    volumes:
      - ./backend/app/media:/app/app/media

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    env_file:
      - ./frontend/.env
      - ./.env
