services:
  ai:
    image: selfstar-ai:latest
    environment:
      - AI_REQUIRE_MODEL=1 # 개발 기본값(폴백 허용). 실제 모델 필수 시 ai/.env 또는 환경변수에서 AI_REQUIRE_MODEL=1 설정
    env_file:
      - ./ai/.env
    ports:
      - "8600:8600"
    restart: unless-stopped

  backend:
    image: selfstar-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai:8600
    depends_on:
      - ai
    volumes:
      - ./backend/app/media:/app/app/media
    restart: unless-stopped

  frontend:
    image: selfstar-frontend:latest
    ports:
      - "5174:5174"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
