version: "3.9"

# Local development stack (no TLS, ports mapped to localhost)
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: selfstar-nginx-dev
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      # Nginx virtual host config for development
      - ./nginx/dev.conf.d:/etc/nginx/conf.d:ro
    networks:
      - dev

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: selfstar-backend-dev
    restart: unless-stopped
    env_file:
      - ./env/backend.dev
    environment:
      # Ensure app knows its own/public URLs for development
      - BACKEND_URL=http://localhost
      - FRONTEND_URL=http://localhost
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips=*", "--timeout-keep-alive", "65"]
    expose:
      - "8000"
    networks:
      - dev
    depends_on:
      - ai
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=3).getcode()==200 else 1)\""]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: selfstar-frontend-dev
    restart: unless-stopped
    env_file:
      - ./env/frontend.dev
    expose:
      - "5174"
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://127.0.0.1:5174',r=>process.exit(0)).on('error',()=>process.exit(1))\""]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  ai:
    build:
      context: ai
      dockerfile: serving/Dockerfile
    container_name: selfstar-ai-dev
    restart: unless-stopped
    env_file:
      - ./env/ai.dev
    expose:
      - "8600"
    networks:
      - dev

networks:
  dev:
    driver: bridge
